2019-12-09T16:58:26|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:26|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:26|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:26|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:26|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:26|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:26|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:26|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:26|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:27|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:27|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:27|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:27|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:27|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:27|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:27|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:27|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:27|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:28|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:28|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:28|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:28|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:28|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:28|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:28|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:28|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:28|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:29|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:29|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:29|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:29|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:29|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:29|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:29|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:29|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:29|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:30|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:30|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:30|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:30|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:30|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:30|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:30|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:31|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:31|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:31|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:31|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:31|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:31|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:32|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:32|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:32|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:32|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:33|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:33|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:33|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:33|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:33|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:34|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:34|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:34|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:34|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:35|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:35|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:35|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:35|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:35|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:36|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:36|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:36|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:36|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:37|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:37|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:37|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:37|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:37|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:38|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:38|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:38|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:38|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:38|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:39|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:39|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:39|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:39|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:40|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:40|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:40|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:40|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:40|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:41|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:41|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:41|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:42|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:42|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:42|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:43|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:43|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:43|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:44|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:44|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:44|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:45|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:45|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:45|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:46|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:46|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:46|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:47|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:47|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:47|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:48|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:48|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:48|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:48|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:49|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:49|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:50|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:50|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:50|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:51|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:51|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:51|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:52|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:52|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:52|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:53|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:53|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:54|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:54|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:55|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:55|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:55|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:56|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:56|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:57|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:57|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:58|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:58|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:59|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:59|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:58:59|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:59:00|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:59:00|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:59:01|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:59:01|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T16:59:02|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
