2019-12-09T17:00:43|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:43|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:43|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:43|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:43|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:44|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:44|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:44|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:44|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:44|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:44|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:44|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:44|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:44|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:45|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:45|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:45|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:45|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:45|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:45|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:45|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:45|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:45|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:46|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:46|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:46|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:46|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:46|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:46|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:46|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:46|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:47|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:47|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:47|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:47|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:47|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:47|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:47|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:47|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:48|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:48|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:48|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:48|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:48|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:48|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:49|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:49|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:49|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:49|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:49|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:50|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:50|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:50|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:50|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:51|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:51|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:51|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:51|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:51|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:52|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:52|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:52|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:52|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:53|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:53|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:53|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:53|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:54|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:54|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:54|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:54|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:54|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:55|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:55|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:55|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:55|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
2019-12-09T17:00:56|ERROR|SineWaveJoyStickMeasure|sine_wave_joystick Failed to update figure1: "['medium']". ['Traceback (most recent call last):\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Matteo\\eclipse-workspace\\scopefoundry\\Microscopes\\VirtualMicroscopeJoyStick\\SineGenJoyStick_measure.py", line 95, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(1 + self.joystick.joystick_dev.get_axis_values(AXIS_R2))\n', 'KeyError: "[\'medium\']"\n']
