2020-03-04T13:40:30|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\LabPrograms\Python\ProChipJoystick\SyncreadoutTriggerJoystickCounterMeasurement.py", line 186, in run
    self.start_triggered_Acquisition(self.settings['Acq_freq'])
  File "C:\LabPrograms\Python\ProChipJoystick\SyncreadoutTriggerJoystickCounterMeasurement.py", line 565, in start_triggered_Acquisition
    self.camera.hamamatsu.startAcquisition()
AttributeError: 'HamamatsuHardware' object has no attribute 'hamamatsu'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\measurement.py", line 25, in run
    self.measurement._thread_run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\measurement.py", line 179, in _thread_run
    self.run()
  File "C:\LabPrograms\Python\ProChipJoystick\SyncreadoutTriggerJoystickCounterMeasurement.py", line 318, in run
    self.stop_triggered_Acquisition()
  File "C:\LabPrograms\Python\ProChipJoystick\SyncreadoutTriggerJoystickCounterMeasurement.py", line 587, in stop_triggered_Acquisition
    self.camera.hamamatsu.stopAcquisition()
AttributeError: 'HamamatsuHardware' object has no attribute 'hamamatsu'

