2020-03-02T16:07:42|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\measurement.py", line 25, in run
    self.measurement._thread_run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\measurement.py", line 179, in _thread_run
    self.run()
  File "C:\LabPrograms\Python\ProChipJoystick\SyncreadoutTriggerJoystickCounterMeasurement.py", line 225, in run
    frameB = self.camera.hamamatsu.getRequiredFrame(self.camera.hamamatsu.buffer_index-1)[0]
  File "C:\LabPrograms\Python\Hamamatsu_ScopeFoundry\CameraDevice.py", line 1284, in getRequiredFrame
    hc_data.copyData(paramlock.buf)
  File "C:\LabPrograms\Python\Hamamatsu_ScopeFoundry\CameraDevice.py", line 309, in copyData
    ctypes.memmove(self.np_array.ctypes.data, address, self.size) #copies self.size bytes from address into self.np_array.ctyps.data
OSError: exception: access violation reading 0x0000000000000000

2020-03-02T16:07:42|ERROR|SyncreadoutTriggerJoystickCounterMeasurement|SyncreadoutTriggerJoystickCounterMeasurement Failed to update figure1: 'JoyStick_HW' object has no attribute 'joystick_dev'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\ProChipJoystick\\SyncreadoutTriggerJoystickCounterMeasurement.py", line 337, in update_display\n    + self.sensitivity_dict[self.settings[\'sensitivity\']]*(self.joystick_hw.joystick_dev.get_axis_values(T_ANALOG)) \\\n', "AttributeError: 'JoyStick_HW' object has no attribute 'joystick_dev'\n"]
