2020-03-04T13:44:31|ERROR|SyncreadoutTriggerJoystickCounterMeasurement|SyncreadoutTriggerJoystickCounterMeasurement Failed to update figure1: 'JoyStick_HW' object has no attribute 'joystick_dev'. ['Traceback (most recent call last):\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\LabPrograms\\Python\\ProChipJoystick\\SyncreadoutTriggerJoystickCounterMeasurement.py", line 379, in update_display\n    if (self.joystick_hw.joystick_dev.get_hat_values(1) or self.joystick_hw.joystick_dev.get_hat_values(0)) and not self.button_pressed_before:\n', "AttributeError: 'JoyStick_HW' object has no attribute 'joystick_dev'\n"]
