2020-03-03T13:50:21|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 208, in enable_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "C:\LabPrograms\Python\joystick_hardware\joystick_hd.py", line 27, in connect
    self.joystick_dev = JoyStickDevice()
  File "C:\LabPrograms\Python\joystick_hardware\joystick_device.py", line 12, in __init__
    self.joystick = pygame.joystick.Joystick(0)
pygame.error: Invalid joystick device number

2020-03-03T13:53:29|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 208, in enable_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "C:\LabPrograms\Python\joystick_hardware\joystick_hd.py", line 27, in connect
    self.joystick_dev = JoyStickDevice()
  File "C:\LabPrograms\Python\joystick_hardware\joystick_device.py", line 12, in __init__
    self.joystick = pygame.joystick.Joystick(0)
pygame.error: Invalid joystick device number

2020-03-03T13:53:31|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 208, in enable_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "C:\LabPrograms\Python\joystick_hardware\joystick_hd.py", line 27, in connect
    self.joystick_dev = JoyStickDevice()
  File "C:\LabPrograms\Python\joystick_hardware\joystick_device.py", line 12, in __init__
    self.joystick = pygame.joystick.Joystick(0)
pygame.error: Invalid joystick device number

2020-03-03T13:53:35|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 208, in enable_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "C:\LabPrograms\Python\joystick_hardware\joystick_hd.py", line 27, in connect
    self.joystick_dev = JoyStickDevice()
  File "C:\LabPrograms\Python\joystick_hardware\joystick_device.py", line 12, in __init__
    self.joystick = pygame.joystick.Joystick(0)
pygame.error: Invalid joystick device number

2020-03-03T13:53:40|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 208, in enable_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "C:\LabPrograms\Python\joystick_hardware\joystick_hd.py", line 27, in connect
    self.joystick_dev = JoyStickDevice()
  File "C:\LabPrograms\Python\joystick_hardware\joystick_device.py", line 12, in __init__
    self.joystick = pygame.joystick.Joystick(0)
pygame.error: Invalid joystick device number

2020-03-03T13:53:48|WARNING|LoggedQuantity|present_output_power read_from_hardware called when not connected to hardware
2020-03-03T13:53:48|WARNING|LoggedQuantity|present_output_power read_from_hardware called when not connected to hardware
2020-03-03T13:54:16|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 208, in enable_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "C:\LabPrograms\Python\joystick_hardware\joystick_hd.py", line 27, in connect
    self.joystick_dev = JoyStickDevice()
  File "C:\LabPrograms\Python\joystick_hardware\joystick_device.py", line 12, in __init__
    self.joystick = pygame.joystick.Joystick(0)
pygame.error: Invalid joystick device number

