2019-12-16T16:44:48|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 208, in enable_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "C:\LabPrograms\Python\joystick_hardware\joystick_hd.py", line 22, in connect
    self.joystick_dev = JoyStickDevice()
  File "C:\LabPrograms\Python\joystick_hardware\joystick_device.py", line 12, in __init__
    self.joystick = pygame.joystick.Joystick(0)
pygame.error: Invalid joystick device number

