2019-12-13T17:34:22|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\LabPrograms\Python\Microscopes\ProChipMicroscopeJoystick\ProChipJoystickApp.py", line 22, in <module>
    app = ProChipJoystickApp(sys.argv)
  File "C:\LabPrograms\Python\BaseMicroscopeModified_ScopeFoundry\BaseMicroscopeAppModified.py", line 16, in __init__
    super().__init__(*kwds) # *kwds is needed since in the main we pass as argument sys.argv. Without
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\base_app.py", line 332, in __init__
    self.setup()
  File "C:\LabPrograms\Python\Microscopes\ProChipMicroscopeJoystick\ProChipJoystickApp.py", line 16, in setup
    super().setup()
  File "C:\LabPrograms\Python\DAQ_Laser_Camera\Laser_DAQ_Camera_App.py", line 10, in setup
    from nidaqmx_test.ni_do_hardware import NI_DO_hw
  File "C:\LabPrograms\Python\nidaqmx_test\ni_do_hardware.py", line 3, in <module>
    from ni_do_device import NI_DO_device
ModuleNotFoundError: No module named 'ni_do_device'

