2019-12-18T12:55:59|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 208, in enable_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "C:\LabPrograms\Python\FluigentHardwareUpdated\PumpHardware.py", line 54, in connect
    self.save_pressure_hardware_set_func = self.MFCS.save_pressure
AttributeError: 'MFCSDevice' object has no attribute 'save_pressure'

2019-12-18T12:56:02|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 208, in enable_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "C:\LabPrograms\Python\FluigentHardwareUpdated\PumpHardware.py", line 54, in connect
    self.save_pressure_hardware_set_func = self.MFCS.save_pressure
AttributeError: 'MFCSDevice' object has no attribute 'save_pressure'

