2019-12-13T12:01:06|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\LabPrograms\Python\Microscopes\ProChipMicroscopeJoystick\ProChipJoystickApp.py", line 22, in <module>
    app = ProChipJoystickApp(sys.argv)
  File "C:\LabPrograms\Python\BaseMicroscopeModified_ScopeFoundry\BaseMicroscopeAppModified.py", line 16, in __init__
    super().__init__(*kwds) # *kwds is needed since in the main we pass as argument sys.argv. Without
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\base_app.py", line 332, in __init__
    self.setup()
  File "C:\LabPrograms\Python\Microscopes\ProChipMicroscopeJoystick\ProChipJoystickApp.py", line 9, in setup
    from joystick_hardware.joystick_hd import JoyStick_HW
  File "C:\LabPrograms\Python\joystick_hardware\joystick_hd.py", line 2, in <module>
    from joystick_hardware.joystick_hd import JoyStickDevice
ImportError: cannot import name 'JoyStickDevice' from 'joystick_hardware.joystick_hd' (C:\LabPrograms\Python\joystick_hardware\joystick_hd.py)

