2019-12-13T17:28:25|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\LabPrograms\Python\Microscopes\ProChipMicroscopeJoystick\ProChipJoystickApp.py", line 22, in <module>
    app = ProChipJoystickApp(sys.argv)
  File "C:\LabPrograms\Python\BaseMicroscopeModified_ScopeFoundry\BaseMicroscopeAppModified.py", line 16, in __init__
    super().__init__(*kwds) # *kwds is needed since in the main we pass as argument sys.argv. Without
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\base_app.py", line 332, in __init__
    self.setup()
  File "C:\LabPrograms\Python\Microscopes\ProChipMicroscopeJoystick\ProChipJoystickApp.py", line 15, in setup
    from Microscopes.ProChipMicroscopeJoystick.SyncreadoutTriggerJoystickMeasurement import SyncreadoutTriggerJoystickMeasurement
  File "C:\LabPrograms\Python\Microscopes\ProChipMicroscopeJoystick\SyncreadoutTriggerJoystickMeasurement.py", line 1, in <module>
    from DAQ_Laser_Camera.SyncreadoutTriggerMeasurement import SyncreadoutTriggerMeasurement
  File "C:\LabPrograms\Python\DAQ_Laser_Camera\SyncreadoutTriggerMeasurement.py", line 2, in <module>
    from CameraMeasurement import HamamatsuMeasurement
ModuleNotFoundError: No module named 'CameraMeasurement'

