2019-12-13T13:17:19|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\LabPrograms\Python\Microscopes\ProChipMicroscopeJoystick\ProChipJoystickApp.py", line 22, in <module>
    app = ProChipJoystickApp(sys.argv)
  File "C:\LabPrograms\Python\BaseMicroscopeModified_ScopeFoundry\BaseMicroscopeAppModified.py", line 16, in __init__
    super().__init__(*kwds) # *kwds is needed since in the main we pass as argument sys.argv. Without
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\base_app.py", line 332, in __init__
    self.setup()
  File "C:\LabPrograms\Python\Microscopes\ProChipMicroscopeJoystick\ProChipJoystickApp.py", line 10, in setup
    from FluigentHardwareUpdated.PumpHardware import MFCSHardware
  File "C:\LabPrograms\Python\FluigentHardwareUpdated\PumpHardware.py", line 3, in <module>
    from FluigentHardwareUpdated.PumpDevice import MFCSDevice
  File "C:\LabPrograms\Python\FluigentHardwareUpdated\PumpDevice.py", line 22, in <module>
    lib_mfcs = ctypes.WinDLL('mfcs_c_64.dll')
  File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] Impossibile trovare il modulo specificato

