2019-12-18T19:08:49|WARNING|LoggedQuantity|set_pressure_1 read_from_hardware called when not connected to hardware
2019-12-18T19:08:55|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\logged_quantity.py", line 241, in update_value
    self.hardware_set_func(self.val)
  File "C:\LabPrograms\Python\FluigentHardwareUpdated\PumpDevice.py", line 124, in set_save_p
    C_error = lib_mfcs.mfcs_set_auto(c_ulonglong(self.mfcsHandle),i,self.saved_pressure[i-1])
ctypes.ArgumentError: argument 3: <class 'TypeError'>: Don't know how to convert parameter 3

2019-12-18T19:08:58|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\logged_quantity.py", line 241, in update_value
    self.hardware_set_func(self.val)
  File "C:\LabPrograms\Python\FluigentHardwareUpdated\PumpDevice.py", line 124, in set_save_p
    C_error = lib_mfcs.mfcs_set_auto(c_ulonglong(self.mfcsHandle),i,self.saved_pressure[i-1])
ctypes.ArgumentError: argument 3: <class 'TypeError'>: Don't know how to convert parameter 3

2019-12-18T19:08:58|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\logged_quantity.py", line 241, in update_value
    self.hardware_set_func(self.val)
  File "C:\LabPrograms\Python\FluigentHardwareUpdated\PumpDevice.py", line 124, in set_save_p
    C_error = lib_mfcs.mfcs_set_auto(c_ulonglong(self.mfcsHandle),i,self.saved_pressure[i-1])
ctypes.ArgumentError: argument 3: <class 'TypeError'>: Don't know how to convert parameter 3

